version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-portfolio"
s3_bucket = "bansi3316"
s3_prefix = "bansi3316"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DynamoDBTableName=\"BansiResume\""
